---
kind: pipeline
name: capirca

steps:
- name: capirca-run
  image: python:3.6
  commands:
  - pip install -r requirements.txt
  - python capirca/aclgen.py --base_directory morales-pol --output_directory morales-pol/acl/
  - ls -al morales-pol/acl/test.asa

- name: pushback
  image: appleboy/drone-git-push
  environment:
    GIT_PUSH_SSH_KEY:
        from_secret: github-ssh-key
  settings:
    remote-name: origin
    remote: git@github.com:nazh/dron-test-2.git
    branch: staging
    local_branch: development

trigger:
  repo:
  - nazh/dron-test-2
  branch:
  - development

