---
kind: pipeline
name: capirca

steps:
- name: capirca-run
  image: python:3.6
  commands:
  - pip install -r requirements.txt
  - cp  cust-pol/acl/test.asa cust-pol/acl/test.bckp
  - python capirca/aclgen.py --base_directory cust-pol --output_directory cust-pol/acl/
  - python capirca/diff.py cust-pol/acl/test.asa cust-pol/acl/test.bckp cust-pol/acl/test.diff

- name: pushback
  image: appleboy/drone-git-push
  environment:
    GIT_PUSH_SSH_KEY:
        from_secret: github-ssh-key
  settings:
    remote-name: origin
    remote: git@github.com:nazh/dron-test-2.git
    branch: staging
    local_branch: development
    commit: true
    commit_message: 'Commit before pushing out'
    force: true

- name: slack2
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack-url 
    channel: grafana_alerts
    username: drone
    template: >
      {{#success build.status}}
        build {{build.number}}, {{build.link}}, {{build.ref}}, {{build.event}} succeeded.
      {{else}}
        build {{build.number}},{{build.commit}} by {{build.author}} failed.
      {{/success}}
  when:
    status: [ success, failure ]

trigger:
  repo:
  - nazh/dron-test-2
  branch:
  - development

