---
kind: pipeline
name: capirca

steps:
- name: capirca-run
  image: python:3.6
  commands:
  - pip install -r requirements.txt
  - cp  morales-pol/acl/test.asa morales-pol/acl/test.bckp
  - python capirca/aclgen.py --base_directory morales-pol --output_directory morales-pol/acl/
  - python capirca/diff.py morales-pol/acl/test.asa morales-pol/acl/test.bckp morales-pol/acl/test.diff

- name: pushback
  image: appleboy/drone-git-push
  environment:
    GIT_PUSH_SSH_KEY:
        from_secret: github-ssh-key
  settings:
    remote-name: origin
    remote: git@github.com:nazh/dron-test-2.git
    branch: staging
    local_branch: development
    commit: true
    commit_message: 'Commit before pushing out'
    force: true

- name: slack-note
  image: plugins/slack
  settings:
    token: 
      from_sercret: slack-tokin
    webhook: https://hooks.slack.com/services/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
    channel: grafana_alerts
    username: drone
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
#  when:
#    status: [ success, failure ]

trigger:
  repo:
  - nazh/dron-test-2
  branch:
  - development

